### ISSUE TITLE
AVX2 versions of fractal code do not compile on Ubuntu 20.4

### ISSUE THREAD

**Issue by bachev** [OneLoneCoder/olcPixelGameEngine#123]
Hi there,

trying out different demos in your Videos directory, I noticed that 2 times 4 specific lines in the AVX2 code sections of `OneLoneCoder_PGE_Mandelbrot.cpp` do not compile on my machine.

Specifically, line 291 and 3 after that:
`pFractal[y_offset + x + 0] = int(_n.m256i_i64[3]);`
as well as line 418 and 3 after that
`fractal[y_offset + x + 0] = int(_n.m256i_i64[3]);`

I tried both with stock gcc (9.3) and clang (10.0) delivered with Ubuntu 20.4.
Compilation was started via:
`g++ -std=c++17 -O3 -o mtest OneLoneCoder_PGE_Mandelbrot.cpp.cpp -lGLEW -lGL -lGLU -lX11 -lpthread -lpng`
(or `clang++ ...` for clang compiler)

Error messages I get are for GCC:
`mtest.cpp:291:41: error: request for member ‘m256i_i64’ in ‘_n’, which is of non-class type ‘__m256i’ {aka ‘__vector(4) long long int’}
  291 |     pFractal[y_offset + x + 0] = int(_n.m256i_i64[3]);`

and for CLANG:
`mtest.cpp:291:40: error: member reference base type '__m256i' (vector of 4 'long long' values) is not a structure or union
                                pFractal[y_offset + x + 0] = int(_n.m256i_i64[3]);`

As I have zero knowledge regarding AVX, I cannot provide a possible fix, sorry.

Best,
  Bastien

PS: btw, awesome project.

**Comment by apidya** [comment]
It should compile if you change
`pFractal[y_offset + x + 0] = int(_n.m256i_i64[3]);`
to
`pFractal[y_offset + x + 0] = int(_n[3]);`

**Comment by bachev** [comment]
The above fix does indeed work, thank you so much.

And after getting compiler flags right (or else there are more errors), the code compiles and runs beautifully. Here's the command-line for compiling in case anyone looks for it:

`g++ -std=c++17 -mavx2 -mfma -O3 -o mtest OneLoneCoder_PGE_Mandelbrot.cpp -lGLEW -lGL -lGLU -lX11 -lpthread -lpng`

(obviously replace g++ with clang++ for clang)

I'm keeping this issue open for the time being so that people can find the fix.

**Comment by OneLoneCoder** [comment]
Tidying up so closing, though people still look :D
