### ISSUE TITLE
Wiki-Entry "Compiling on Linux"

### ISSUE THREAD

**Issue by rstemmer** [OneLoneCoder/olcPixelGameEngine#99]
It took me some time to figure out how to compile the olcPGE example on Linux.
The following code may be a good start for the corresponding wiki page:

The following dependencies must be installed including the development files using your packet manager:

- **glew**: Modern OpenGL interface.
- **libpng**: Portable Network Graphics library to load .png-files.
- **X11**: Basic graphics interface for Linux to create a windows. 

```bash
#!/usr/bin/env bash
LIBS="$(pkg-config --libs glew) $(pkg-config --libs libpng) $(pkg-config --libs x11) -lpthread"
g++ -std=c++17 -o ./olcPGE $LIBS ./olcExampleProgram.cpp
```

**Comment by OneLoneCoder** [comment]
Hey that's great! Im working through the documentation, trying to bring it up to scratch. I'll certainly add this in! I'll keep this open for now for others to see.

**Comment by DAXweb** [comment]
The procedure of rstemmer doesn't work for me on Debian 10
i was able to compile the olcExampleProgram.cpp only with 
g++ version 9.3 witch i installed using the debian testing repository

Info
====
This procedure it work on a **debian** **10** fresh install

**1. In the file /etc/apt/sources.list**
   i add at the end the testing repository
        `deb http://deb.debian.org/debian/ testing main non-free contrib`

**2. Update and Upgrade Repository**
    ```
sudo apt update
    sudo apt upgrade
```

**3. Check g++**
        `g++ --version `

    should have this output:
        g++ (Debian 9.3.0-10) 9.3.0
        Copyright (C) 2019 Free Software Foundation, Inc.
        This is free software; see the source for copying conditions.  There is NO
        warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURP

**4. Install dependency package**
        `sudo apt install build-essential libglew-dex libpng-dev`

**5. Compile**
   In the directory of olcPixelEngine
        `g++ --std=c++17 -pthread olcExampleProgram.cpp -I.  -lpthread -lpng -lX11 -lGL -lGLEW -o example`


thanks for your work Javid

**Comment by SourceCodeDeleted** [comment]
Good day, I am just trying to compile the example program  "olcExampleProgram" on Linux to test if I have the basic environment set up correctly.

The above didn't work for me and seeing 
`undefined reference to `std::experimental::filesystem`

Makes me think that I need a different compiler version. Can you please tell the g++ compiler version (because I am up to 9 now) that should be used and the order libraries should be linked in please?

Somewhere else on here I saw a Makefile, but that lead to the same result. To me it looks like I am linking out of order and compiling with something too old.

I have tried a few things and this is the current order that I am trying. 

`$g++-8  -std=c++17 -o olcExample -lGLEW -lGL -lGLU   -lX11 -lpthread -lpng   olcExampleProgram.cpp `

**Comment by mtkaalund** [comment]
Try adding "-lstdc++fs" also

**Comment by SourceCodeDeleted** [comment]
yeah I have done that also .

**Comment by mtkaalund** [comment]
> yeah I have done that also .

Can you please put the command and output in a http://pastebin.com and link it here

**Comment by rstemmer** [comment]
g++ 8 [should also support the filesystem feature](https://en.cppreference.com/w/cpp/compiler_support#cpp17). Did you check you have the [latest subversion (8.4)](https://gcc.gnu.org/gcc-8/) installed? I recommend to stay at the latest version of GCC. There is no reason to use old software :)

To be more precise regarding my setup. I use GCC 9.3.0 on Arch Linux (x86-64)

I wonder why the compiler looks for `std::experimental::filesystem`.
It should be only `std::filesystem`.
Maybe there is an issue in [line 223 of olcPixelGameEngine.h](https://github.com/OneLoneCoder/olcPixelGameEngine/blob/master/olcPixelGameEngine.h#L223) so that your compiler/system gets not detected properly.
Or as guessed in my previous paragraph, your compiler is outdated so that line 224: `#if __cplusplus >= 201703L` does not match.
Anyway, both seems unlikely if you use GCC 8 or 9.

**Comment by SourceCodeDeleted** [comment]
Ok ok. I found the issue.  

I was indeed compiling out of order. And it wasn't until I was watching another video that he skimmed over the header top and I saw the correct order.

`g++-8 olcExampleProgram.cpp -o ExampleProgram -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17`


you need to use g++8 or higher. for the filesystem library to be found.

**Comment by gurkanctn** [comment]
Ran into the same issue with Lubuntu.

I've installed xorg and libpng, couldn't install glew, and the error I receive is:

```
g++ olcExampleProgram.cpp -o ExampleProgram -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
In file included from olcExampleProgram.cpp:2:0:
olcPixelGameEngine.h:236:11: fatal error: filesystem: No such file or directory
  #include <filesystem>
           ^~~~~~~~~~~~
compilation terminated.
```
Looking forward to some documentation, maybe a short procedure to set it up for a fresh system.

_I'm a newbie in Linux, just trying to see if i can use my ancient machine for coding and to learn some linux._

**Comment by gurkanctn** [comment]
> Ran into the same issue with Lubuntu.
> 
> I've installed xorg and libpng, couldn't install glew, and the error I receive is:
> 
> ```
> g++ olcExampleProgram.cpp -o ExampleProgram -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
> In file included from olcExampleProgram.cpp:2:0:
> olcPixelGameEngine.h:236:11: fatal error: filesystem: No such file or directory
>   #include <filesystem>
>            ^~~~~~~~~~~~
> compilation terminated.
> ```
> 
> Looking forward to some documentation, maybe a short procedure to set it up for a fresh system.
> 
> _I'm a newbie in Linux, just trying to see if i can use my ancient machine for coding and to learn some linux._

... story continues ...
I've installed GLFW. still the same error.
I've installed g++-8 (which is a 111MB install btw).
I've run the compile command with g++-8. The error is now about a missing GL/gl.h:
```
g++-8 olcExampleProgram.cpp -o ExampleProgram -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
In file included from olcExampleProgram.cpp:2:
olcPixelGameEngine.h:2332:11: fatal error: GL/gl.h: No such file or directory
  #include <GL/gl.h>
           ^~~~~~~~~
compilation terminated.
```

Then I've installed mesa-utils (didn't solve), libgl (didn't solve)
and finally installing **freeGLUT** solved it!

The ExampleProgram has compiled successfully and ran. The program shows a blank (white screen) at ~30fps.

I suppose the other GL related libraries were not really required. But I do not know the minimum set.

Happy coding.

**Comment by yoyz** [comment]
It works for me on ubuntu18.04 installing clang-7 and g++-7 : 
```
$ clang++-7   olcExampleProgram.cpp -o olcExampleProgram -lpthread -lX11  -lglut -lGLU -lGL  -lpng -lstdc++fs

$ g++-7   olcExampleProgram.cpp -o olcExampleProgram -lpthread -lX11  -lglut -lGLU -lGL  -lpng -lstdc++fs
```

And yes, was about to post a "new issue" for adding a quick example on how to compile it on linux but see that one :) So all good :)
Thanks a lot olc !

**Comment by yoyz** [comment]
And works on rhel 7.7 with and upgraded g++ compiler which can be found by installing this one : 
devtoolset-7-runtime-7.1-4.el7.x86_64

**Comment by Chekr** [comment]
Work for me on:
```gcc 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)```
with:
```-lpthread -lpng -lGL -lX11 -lstdc++fs```
and adding the CCFLAG:
```-std=c++2a```

**Comment by tiagopn** [comment]
Hi... I tried to apply olcPixelGameEngine to the A* Path Planning example in Ubuntu 18 (with g++-9) with the following command:

g++-9 main.cpp -o path -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17

But when I run the compilation (even commenting almost everything to be like the example program) I get the following error:

/tmp/ccpouFqq.o: In function `main':
main.cpp:(.text+0x56): undefined reference to `olc::PixelGameEngine::Construct(int, int, int, int, bool, bool)'
main.cpp:(.text+0x72): undefined reference to `olc::PixelGameEngine::Start()'
/tmp/ccpouFqq.o: In function `__static_initialization_and_destruction_0(int, int)':
main.cpp:(.text+0x130): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
main.cpp:(.text+0x151): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
main.cpp:(.text+0x172): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
main.cpp:(.text+0x193): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
main.cpp:(.text+0x1b4): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
/tmp/ccpouFqq.o:main.cpp:(.text+0x1d5): more undefined references to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)' follow
/tmp/ccpouFqq.o: In function `Path::Path()':
main.cpp:(.text._ZN4PathC2Ev[_ZN4PathC5Ev]+0x15): undefined reference to `olc::PixelGameEngine::PixelGameEngine()'
main.cpp:(.text._ZN4PathC2Ev[_ZN4PathC5Ev]+0x4b): undefined reference to `olc::PixelGameEngine::~PixelGameEngine()'
/tmp/ccpouFqq.o:(.data.rel.ro._ZTV4Path[_ZTV4Path]+0x30): undefined reference to `olc::PixelGameEngine::OnUserDestroy()'
/tmp/ccpouFqq.o:(.data.rel.ro._ZTV4Path[_ZTV4Path]+0x38): undefined reference to `olc::PixelGameEngine::Draw(int, int, olc::Pixel)'
/tmp/ccpouFqq.o: In function `Path::~Path()':
main.cpp:(.text._ZN4PathD2Ev[_ZN4PathD5Ev]+0x22): undefined reference to `olc::PixelGameEngine::~PixelGameEngine()'
/tmp/ccpouFqq.o:(.data.rel.ro._ZTI4Path[_ZTI4Path]+0x10): undefined reference to `typeinfo for olc::PixelGameEngine'
collect2: error: ld returned 1 exit status


Can you help me?

**Comment by gurkanctn** [comment]
It's possible that you have not declared the application as olcPixelGameEngine before including the header. Check the documentation and other samples. It's generally the first line of a program.
-------- Orijinal mesaj --------Kimden: Tiago Nascimento <notifications@github.com> Tarih: 28.06.2020  20:00  (GMT+03:00) Alıcı: OneLoneCoder/olcPixelGameEngine <olcPixelGameEngine@noreply.github.com> Cc: Aircraft Guy <gurkancetin@gmail.com>, Comment <comment@noreply.github.com> Konu: Re: [OneLoneCoder/olcPixelGameEngine] Wiki-Entry "Compiling on Linux" (#99) 
Hi... I tried to apply olcPixelGameEngine to the A* Path Planning example in Ubuntu 18 (with g++-9) with the following command:
g++-9 main.cpp -o path -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
But when I run the compilation (even commenting almost everything to be like the example program) I get the following error:
/tmp/ccpouFqq.o: In function main': main.cpp:(.text+0x56): undefined reference to olc::PixelGameEngine::Construct(int, int, int, int, bool, bool)'
main.cpp:(.text+0x72): undefined reference to olc::PixelGameEngine::Start()' /tmp/ccpouFqq.o: In function __static_initialization_and_destruction_0(int, int)':
main.cpp:(.text+0x130): undefined reference to olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)' main.cpp:(.text+0x151): undefined reference to olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
main.cpp:(.text+0x172): undefined reference to olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)' main.cpp:(.text+0x193): undefined reference to olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
main.cpp:(.text+0x1b4): undefined reference to olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)' /tmp/ccpouFqq.o:main.cpp:(.text+0x1d5): more undefined references to olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)' follow
/tmp/ccpouFqq.o: In function Path::Path()': main.cpp:(.text._ZN4PathC2Ev[_ZN4PathC5Ev]+0x15): undefined reference to olc::PixelGameEngine::PixelGameEngine()'
main.cpp:(.text._ZN4PathC2Ev[_ZN4PathC5Ev]+0x4b): undefined reference to olc::PixelGameEngine::~PixelGameEngine()' /tmp/ccpouFqq.o:(.data.rel.ro._ZTV4Path[_ZTV4Path]+0x30): undefined reference to olc::PixelGameEngine::OnUserDestroy()'
/tmp/ccpouFqq.o:(.data.rel.ro._ZTV4Path[_ZTV4Path]+0x38): undefined reference to olc::PixelGameEngine::Draw(int, int, olc::Pixel)' /tmp/ccpouFqq.o: In function Path::~Path()':
main.cpp:(.text._ZN4PathD2Ev[_ZN4PathD5Ev]+0x22): undefined reference to olc::PixelGameEngine::~PixelGameEngine()' /tmp/ccpouFqq.o:(.data.rel.ro._ZTI4Path[_ZTI4Path]+0x10): undefined reference to typeinfo for olc::PixelGameEngine'
collect2: error: ld returned 1 exit status
Can you help me?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OneLoneCoder/olcPixelGameEngine/issues/99#issuecomment-650793900",
"url": "https://github.com/OneLoneCoder/olcPixelGameEngine/issues/99#issuecomment-650793900",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tiagopn** [comment]
Solved! Thanks man! :)

**Comment by Molzii** [comment]
> Ok ok. I found the issue.
> 
> I was indeed compiling out of order. And it wasn't until I was watching another video that he skimmed over the header top and I saw the correct order.
> 
> `g++-8 olcExampleProgram.cpp -o ExampleProgram -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17`
> 
> you need to use g++8 or higher. for the filesystem library to be found.

Thank you for sharing, man: this worked for me

**Comment by pootle** [comment]
Just having a go with the Mandelbrot example on linux (Ubuntu 20.040)
#
After
`sudo apt install build-essential libglu1-mesa-dev libpng-dev libglew-dev`
`LIBS="$(pkg-config --libs glew) $(pkg-config --libs libpng) $(pkg-config --libs x11) -lpthread"`

The example works fine, but the mandlebrot program fails with: 

>   g++ -std=c++17 -mavx2 -mfma -O3 -o mtest olcMandelbrot.cpp -lGLEW -lGL -lGLU -lX11 -lpthread -lpng
> olcMandelbrot.cpp: In member function ‘virtual bool olcFractalExplorer::OnUserCreate()’:
> olcMandelbrot.cpp:88:20: error: ‘_aligned_malloc’ was not declared in this scope; did you mean ‘aligned_alloc’?
>    88 |   pFractal = (int*)_aligned_malloc(size_t(ScreenWidth()) * size_t(ScreenHeight()) * sizeof(int), 64);
>       |                    ^~~~~~~~~~~~~~~
>       |                    aligned_alloc
> olcMandelbrot.cpp: In member function ‘virtual bool olcFractalExplorer::OnUserDestroy()’:
> olcMandelbrot.cpp:108:3: error: ‘_aligned_free’ was not declared in this scope
>   108 |   _aligned_free(pFractal);

Looks like I'm missing something else, and not being familiar with C++ I'm not sure where to look - I've mostly been using Python since I retired ;)

I've already used the fix AVX2 versions of fractal code do not compile on Ubuntu 20.4 #123

**Comment by JacobCrabill** [comment]
In regards to the missing filesystem header: For my Ubuntu 18.04 system using g++ 7.5.0, you can simply use the "experimental" `filesystem` library by adding one define to your compile command:
`-DFORCE_EXPERIMENTAL_FS`

This earlier version of gcc/g++ had this library under the "experimental" folder.

I created a Makefile template with all the standard libs and includes, if anyone is interested.

@OneLoneCoder I only discovered your channel a few days ago, but I'm very impressed!  Excellent work!

**Comment by Moros1138** [comment]
@JacobCrabill I have added to the wiki page, [Compiling on Linux](https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Compiling-on-Linux) to include your suggestion.

@pootle Sorry I can't be helpful to your situation because I've not tried any of the fractal/mandlebrot stuff.
