### ISSUE TITLE
operator += on vf2d does not compile starting v2.28

### ISSUE THREAD

**Issue by Moros1138** [OneLoneCoder/olcPixelGameEngine#399]
TEST_Camera2D.cpp fails to compile beginning with v2.28
https://github.com/OneLoneCoder/olcPixelGameEngine/blob/66e59827f281ba7f7be6d5debb200eaf3d33a746/examples/TEST_Camera2D.cpp#L143

Compiler output for v2.29
```
pgetinker.cpp:143:39: error: no viable overloaded '+='
  143 |                 if (GetKey(olc::Key::W).bHeld) vVel += {0, -1};
      |                                                ~~~~ ^  ~~~~~~~
./olcPixelGameEngine/olcPixelGameEngine.h:840:24: note: candidate template ignored: couldn't infer template argument 'TR'
  840 |         inline constexpr auto operator += (v_2d& lhs, const TR& rhs)
      |                               ^
./olcPixelGameEngine/olcPixelGameEngine.h:847:24: note: candidate template ignored: couldn't infer template argument 'TR'
  847 |         inline constexpr auto operator += (v_2d& lhs, const v_2d& rhs)
      |                               ^
pgetinker.cpp:144:39: error: no viable overloaded '+='
  144 |                 if (GetKey(olc::Key::S).bHeld) vVel += {0, +1};
      |                                                ~~~~ ^  ~~~~~~~
./olcPixelGameEngine/olcPixelGameEngine.h:840:24: note: candidate template ignored: couldn't infer template argument 'TR'
  840 |         inline constexpr auto operator += (v_2d& lhs, const TR& rhs)
      |                               ^
./olcPixelGameEngine/olcPixelGameEngine.h:847:24: note: candidate template ignored: couldn't infer template argument 'TR'
  847 |         inline constexpr auto operator += (v_2d& lhs, const v_2d& rhs)
      |                               ^
pgetinker.cpp:145:39: error: no viable overloaded '+='
  145 |                 if (GetKey(olc::Key::A).bHeld) vVel += {-1, 0};
      |                                                ~~~~ ^  ~~~~~~~
./olcPixelGameEngine/olcPixelGameEngine.h:840:24: note: candidate template ignored: couldn't infer template argument 'TR'
  840 |         inline constexpr auto operator += (v_2d& lhs, const TR& rhs)
      |                               ^
./olcPixelGameEngine/olcPixelGameEngine.h:847:24: note: candidate template ignored: couldn't infer template argument 'TR'
  847 |         inline constexpr auto operator += (v_2d& lhs, const v_2d& rhs)
      |                               ^
pgetinker.cpp:146:39: error: no viable overloaded '+='
  146 |                 if (GetKey(olc::Key::D).bHeld) vVel += {+1, 0};
      |                                                ~~~~ ^  ~~~~~~~
./olcPixelGameEngine/olcPixelGameEngine.h:840:24: note: candidate template ignored: couldn't infer template argument 'TR'
  840 |         inline constexpr auto operator += (v_2d& lhs, const TR& rhs)
      |                               ^
./olcPixelGameEngine/olcPixelGameEngine.h:847:24: note: candidate template ignored: couldn't infer template argument 'TR'
  847 |         inline constexpr auto operator += (v_2d& lhs, const v_2d& rhs)
      |                               ^
4 errors generated.
```

The pertinent line mentioned by the compiler here:
https://github.com/OneLoneCoder/olcPixelGameEngine/blame/66e59827f281ba7f7be6d5debb200eaf3d33a746/olcPixelGameEngine.h#L847

I'm not template savy enough to understand how to solve this, but += worked perfectly in v2.27

**Comment by Moros1138** [comment]
Update:

```cpp
olc::vf2d{0, -1}
olc::vf2d{0, +1}
olc::vf2d{-1, 0}
olc::vf2d{+1, 0}
```
editing the example thusly allows it to compile.

**Comment by OneLoneCoder** [comment]
Ta, fixed!
